sudo: required 
services:
    - docker

before-install:
    - docker build -t vishwaspuri/docker-react-travis -f Dockerfile.dev .
    
scripts:
    - docker run -e CI=true vishwaspuri/docker-react-travis npm run test   

deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-south-1-845328738252"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"

        